# Use official Python image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

#Move to /Django Project directory
#WORKDIR /app/profileapi

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Collect static files (optional for Django)
RUN python manage.py collectstatic --noinput || true

# Expose port
EXPOSE 8080

# Start server
#ENV DJANGO_SETTINGS_MODULE = profileapi.settings
CMD ["gunicorn", "profileapi.wsgi:application", "--bind", "0.0.0.0:8080"]
